### ISSUE TITLE
Currently Selected Datapack Error, Game Crashes, Stucking with Saving The World... This mod has worse things that can happen to a mod together!

### ISSUE THREAD

**Issue by Blunder-G** [SmileycorpMC/follow-me#3]
Firstly: When am in Main Menu, game crashes and Not Enough Crashes tells me the this mods (FPS Reducer, Carry On, Follow Me) causes the problem.

Secondly: When i try to make new world, game says me "Currently Selected Datapacks Prevent The World From Loading"

Thirdly: After the game says that, game stucks on Saving World and crashes...

Crash Reports: 
[crash-2021-08-04_20.00.34-client.txt](https://github.com/SmileycorpMC/follow-me/files/6933615/crash-2021-08-04_20.00.34-client.txt)
[crash-2021-08-04_20.53.11-client.txt](https://github.com/SmileycorpMC/follow-me/files/6933616/crash-2021-08-04_20.53.11-client.txt)

Log: 
[latest.log](https://github.com/SmileycorpMC/follow-me/files/6933617/latest.log)

**Comment by SmileycorpMC** [comment]
I am working on a fix for the next update, which should be out soon.

**Comment by SmileycorpMC** [comment]
fixed as of version 1.16.5-1.1.4
