### ISSUE TITLE
1.16.5 doesn't work

### ISSUE THREAD

**Issue by Rakiw** [SmileycorpMC/follow-me#4]
Whenever i add a mob into the config file i cannot start the game beacuse it crashes.

**Comment by SmileycorpMC** [comment]
Woudl you be able to send what's in your config file plus the log?

When does it crash?

**Comment by Rakiw** [comment]
This is what i put into the config file (github doesn't support .toml files so i coppied the script):


```
[general]
	#Entities that follow the player after sneak right-clicked. (uses either classname e.g. ZombieEntity or registry name e.g. minecraft:zombie)
	entityWhitelist = [minecraft:villager,minecraft:iron_golem,minecraft:snow_golem]
```


[crash-2021-08-12_16.33.59-client.txt](https://github.com/SmileycorpMC/follow-me/files/6976264/crash-2021-08-12_16.33.59-client.txt)
[latest.log](https://github.com/SmileycorpMC/follow-me/files/6976273/latest.log)

Here are the files you asked for, i'm not sure why the month is in polish but i don't think it's a problem at all. Also there is a list of all the mods i used in these to files.

The game loading was normal but in the moment the main menu should have opened, i saw this:
![IMG_20210812_165118](https://user-images.githubusercontent.com/88189636/129218691-ddc8bbee-b5af-4f71-9a5f-2008db01815d.jpg)
And then the game crashed.

I hope I anwsered all you questions.
Also just in case you should know, i am using Tlauncher.

**Comment by SmileycorpMC** [comment]
I was moreso looking for the latest.log file in your logs folder as the mod should spit out any errors in there instead of crashing.

The formatting looks a bit weird to me as well, If you can send the logs I'll take a look and see if I can find the issue.

**Comment by SmileycorpMC** [comment]
The formatting in your config file is wrong, each entry in the config should be in the string format e.g "minecraft:villager", "VillagerEntity", with the speach marks included.

**Comment by Rakiw** [comment]
This is what i put into the config file (github doesn't support .toml files so i coppied the script):


```
[general]
	#Entities that follow the player after sneak right-clicked. (uses either classname e.g. ZombieEntity or registry name e.g. minecraft:zombie)
	entityWhitelist = [minecraft:villager,minecraft:iron_golem,minecraft:snow_golem]
```


[crash-2021-08-12_16.33.59-client.txt](https://github.com/SmileycorpMC/follow-me/files/6976264/crash-2021-08-12_16.33.59-client.txt)
[latest.log](https://github.com/SmileycorpMC/follow-me/files/6976273/latest.log)

Here are the files you asked for, i'm not sure why the month is in polish but i don't think it's a problem at all. Also there is a list of all the mods i used in these to files.

The game loading was normal but in the moment the main menu should have opened, i saw this:
![IMG_20210812_165118](https://user-images.githubusercontent.com/88189636/129218691-ddc8bbee-b5af-4f71-9a5f-2008db01815d.jpg)
And then the game crashed.

I hope I anwsered all you questions.
Also just in case you should know, i am using Tlauncher.

**Comment by Rakiw** [comment]
Yes it is working, thanks for help.
I would suggest you changing the note in the config file by surrounding ZombieEntity and minecraft:zombie with quotation marks.
It would look like this:
```
[general]
	#Entities that follow the player after sneak right-clicked. (uses either classname e.g. "ZombieEntity" or registry name e.g. "minecraft:zombie")
	entityWhitelist = []
```
With this change it will be clearer for the users how they are supposed to do the formatting.
