### ISSUE TITLE
[1.16.5] mod version 1.14 makes server crash but 1.13 works fine

### ISSUE THREAD

**Issue by raffle2** [SmileycorpMC/follow-me#5]
Hey first of all thank you for creating this mod!
I recently updated your mod to the latest version but i can't run my server at all and get this crash: https://i.imgur.com/yb00Hg7.png

If I revert back to 1.13 it works fine though

**Comment by SmileycorpMC** [comment]
Would you be able to send the full crash report, so I might better be able to find where the issue is?

**Comment by raffle2** [comment]
Yes my bad! Here you go https://mclo.gs/J462Kp4

**Comment by SmileycorpMC** [comment]
This is now fixed as of release 1.1.4a.

**Comment by raffle2** [comment]
Yep it's working great now, thank you so much <3
