### ISSUE TITLE
Strange void-like terrain

### ISSUE THREAD

**Issue by Kasia1403** [SmileycorpMC/follow-me#9]
![2022-04-15_12 16 49](https://user-images.githubusercontent.com/54236098/163564842-1c8c5c02-b790-45e4-a749-350294b3ff90.png)

**Comment by Kasia1403** [comment]
Is it cused by Your mod or wchich one ?

latest.log

[latest.log](https://github.com/SmileycorpMC/follow-me/files/8495610/latest.log)

**Comment by SmileycorpMC** [comment]
I don't know which mod would be causing it, but it looks like desync with the internal server.

It's nothing follow me would be able to cause really.

**Comment by Kasia1403** [comment]
How to sync with internal server ?
